[tool.poetry]
name = "ruv"
version = "0.1.0"
description = ""
authors = ["Paul Burt <peeb@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
babel = "^2.12.1"
httpx = "^0.24.1"
jinja2 = "^3.1.2"
pydantic = "^2.0"
starlette = "^0.28.0"
uvicorn = "^0.22.0"

[tool.pyright]
reportUnknownMemberType = false
venv = ".venv"
venvPath = "."

[tool.pyright.analysis]
typeCheckingMode = "strict"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
